export const HOME_SAVE_THOUGHT_BEGIN = 'HOME_SAVE_THOUGHT_BEGIN';
export const HOME_SAVE_THOUGHT_SUCCESS = 'HOME_SAVE_THOUGHT_SUCCESS';
export const HOME_SAVE_THOUGHT_FAILURE = 'HOME_SAVE_THOUGHT_FAILURE';
export const HOME_SAVE_THOUGHT_DISMISS_ERROR = 'HOME_SAVE_THOUGHT_DISMISS_ERROR';
export const HOME_SUGGEST_THOUGHT_BEGIN = 'HOME_SUGGEST_THOUGHT_BEGIN';
export const HOME_SUGGEST_THOUGHT_SUCCESS = 'HOME_SUGGEST_THOUGHT_SUCCESS';
export const HOME_SUGGEST_THOUGHT_FAILURE = 'HOME_SUGGEST_THOUGHT_FAILURE';
export const HOME_SUGGEST_THOUGHT_DISMISS_ERROR = 'HOME_SUGGEST_THOUGHT_DISMISS_ERROR';
